version: '3.4'

services:
 
  service_sqlserver:
    user: root
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Mehmet123!
    volumes:
      - sqlserver_data:/var/opt/mssql/data
      - sqlserver_log:/var/opt/mssql/log
    networks:
      - net_backendservices

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "50010:50010"

  diet.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "50011:50011"

networks:
  net_apigateway:
    driver: bridge
    external: true
  net_frontend:
    driver: bridge
    external: true
  net_backendservices:
    driver: bridge
    external: true

volumes:
  rabbitmq:
  sqlserver_data:
  sqlserver_log:
